title: Kai Bailey
logo: /assets/img/headshot.png
theme: jekyll-theme-minimal
#social-network-links:
 # email: "kai.bailey@live.com"
 # github: kaibailey2
 # linkedin: [Kai Bailey](www.linkedin.com/in/kai-bailey-67a480262)
